name: Dave Page
favicon: null
layout_spectrum: 0.2119960030540824
typography_spectrum: 0.7949782777577639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.503003416582942
  lightness: 0.37112798006273806
  saturation: 0.6939861821010709
  rhythmicContrast: 0.2911166751291603
purpose: []
